services:
  - type: web
    name: ecohaul-backend
    env: node
    plan: free
    buildCommand: npm install && npm rebuild bcrypt --build-from-source
    startCommand: node index.js
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false 